### ISSUE TITLE
Dataloaders Information

### ISSUE THREAD

**Issue by cristian-tamblay** [DashAISoftware/DashAI#95] opened 2023-06-12 16:26 UTC
* Python version: 3.8
* Operating System: Ubuntu 20.04

### Description

I was trying to upload a dataset. There is no longer a description for the dataloaders, something broke.

### What I Did

![image](https://github.com/DashAISoftware/DashAI/assets/30818944/fdee700c-52ad-44a4-ab64-a234c2235140)

**Comment by maximi4321** [comment] 2023-06-12 19:10
Thank you, I think the issue is only related to the frontend.

When I started working, the data such as the schema and description of the components were not available, that's why they were missing in the modal.

A description was added for the tasks, so it now appears in the modal, but for the dataloaders, the description is inside the "schema" property.

The problem should be solved when #101 is merged.

**Closed as completed** 2023-06-16 18:40 UTC
